name: BernardTardis
version: 0.1
author: João Bernardi — @jaobernardi
main: space.jaobernardi.tardis.BernardTardis
api-version: 1.18
commands:
  tardis:
    permission: bernardtardis.commands.tardis
    description: "Bernard's TARDIS commands"